language: python
sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

branches:
  only:
    - next-dev

before_install:
  - pip install awscli
  - docker build -t guanyu-product-web -f ./web/Dockerfile .
  - docker build -t guanyu-product-fetch -f ./fetch/Dockerfile .
  - docker build -t guanyu-product-sophosav -f ./sophosav/Dockerfile .

script:
  - $(aws ecr get-login --no-include-email --region ap-northeast-1)
  - docker tag guanyu-product-web:latest 408772917132.dkr.ecr.ap-northeast-1.amazonaws.com/guanyu-web:$SHA
  - docker tag guanyu-product-fetch:latest 408772917132.dkr.ecr.ap-northeast-1.amazonaws.com/guanyu-fetch:$SHA
  - docker tag guanyu-product-sophosav:latest 408772917132.dkr.ecr.ap-northeast-1.amazonaws.com/guanyu-sophosav:$SHA
  - docker push 408772917132.dkr.ecr.ap-northeast-1.amazonaws.com/guanyu-web:$SHA
  - docker push 408772917132.dkr.ecr.ap-northeast-1.amazonaws.com/guanyu-fetch:$SHA
  - docker push 408772917132.dkr.ecr.ap-northeast-1.amazonaws.com/guanyu-sophosav:$SHA

after_success:
  - sed -ri "s/WebImageTag-SHA/$SHA/" ./_cfn/config.json
  - sed -ri "s/FetchImageTag-SHA/$SHA/" ./_cfn/config.json
  - sed -ri "s/SophosavImageTag-SHA/$SHA/" ./_cfn/config.json
  - aws cloudformation update-stack --stack-name GuanyuPromoteTestStack --use-previous-template --parameters file://./_cfn/config.json